# Generated by Django 4.1.4 on 2022-12-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_rename_decription_tutorial_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='created_date',
            new_name='created',
        ),
    ]
